
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.CruzZapil.CompiFinal.gramatica;

/** CUP generated interface containing symbol constants. */
public interface symbol {
  /* terminals */
  public static final int COMILLAS = 2;
  public static final int LEFT = 72;
  public static final int AQUA = 60;
  public static final int HEXADECIMAL = 61;
  public static final int DIVISION = 112;
  public static final int MENOR_IGUAL = 102;
  public static final int MENOR_QUE = 101;
  public static final int TYPE = 76;
  public static final int H1 = 39;
  public static final int CORCHETE_DER = 6;
  public static final int MARRON = 50;
  public static final int TEAL = 47;
  public static final int RIGHT = 73;
  public static final int HEAD_C = 14;
  public static final int LLAVE_IZQ = 3;
  public static final int ROWS = 84;
  public static final int PARENTESIS_DER = 8;
  public static final int ASC = 113;
  public static final int CHECKBOX = 80;
  public static final int NAME = 82;
  public static final int MAYOR = 10;
  public static final int SANS_SERIF = 70;
  public static final int INIT = 122;
  public static final int ALT = 89;
  public static final int BLUE = 49;
  public static final int YELLOW = 59;
  public static final int FUCHSIA = 54;
  public static final int WHITE = 56;
  public static final int TEXT_ALIGN = 71;
  public static final int LETIMPAR_NUM = 115;
  public static final int BLACK = 45;
  public static final int MAYOR_QUE = 103;
  public static final int JUSTITY = 75;
  public static final int IMG_C = 34;
  public static final int GRAY = 52;
  public static final int NOT = 107;
  public static final int BACKGROUND = 44;
  public static final int CENTER = 74;
  public static final int TEXT = 77;
  public static final int THENWHILE = 131;
  public static final int SPAN_C = 22;
  public static final int THEN = 124;
  public static final int HTML_C = 12;
  public static final int HTML = 11;
  public static final int WIDTH = 87;
  public static final int PURPLE = 57;
  public static final int REVERSE = 116;
  public static final int BR_C = 36;
  public static final int CLASS = 85;
  public static final int ALERT_INFO = 119;
  public static final int NUMBER = 78;
  public static final int REDIRECT = 121;
  public static final int NUM_ALEATORIO = 118;
  public static final int HUNTIL = 128;
  public static final int CARACTER_RAMD = 117;
  public static final int PIXEL = 64;
  public static final int PLUS = 111;
  public static final int IGUAL = 108;
  public static final int OLIVE = 46;
  public static final int WHILE = 130;
  public static final int COLS = 83;
  public static final int CORCHETE_IZQ = 5;
  public static final int CHAR = 97;
  public static final int DECIMAL = 95;
  public static final int BOOLEAN = 96;
  public static final int INPUT = 23;
  public static final int PARENTESIS_IZQ = 7;
  public static final int INTERGER = 94;
  public static final int DIV = 31;
  public static final int NAVY = 51;
  public static final int H1_C = 40;
  public static final int P = 41;
  public static final int ELSE = 126;
  public static final int MENOR = 9;
  public static final int COURIER = 66;
  public static final int DIV_C = 32;
  public static final int DESIGUALDAD = 100;
  public static final int LINK = 17;
  public static final int EOF = 0;
  public static final int TEXTOAREA_C = 26;
  public static final int ARIAL = 68;
  public static final int TITLE_C = 16;
  public static final int SUMA = 109;
  public static final int LLAVE_DER = 4;
  public static final int BUTTON = 37;
  public static final int BODY_C = 20;
  public static final int REPEAT = 127;
  public static final int FUNTION = 132;
  public static final int SPAM = 21;
  public static final int VERDANA = 67;
  public static final int TEXTOAREA = 25;
  public static final int P_C = 42;
  public static final int GENEVA = 69;
  public static final int SCRIPTING = 91;
  public static final int SRC = 86;
  public static final int BODY = 19;
  public static final int HREF = 43;
  public static final int TITLE = 15;
  public static final int OR = 105;
  public static final int EXIT = 120;
  public static final int error = 1;
  public static final int RESTA = 110;
  public static final int OPTION_C = 30;
  public static final int IF = 123;
  public static final int DESC = 114;
  public static final int ID = 81;
  public static final int COLOR = 62;
  public static final int ON_LOAD = 93;
  public static final int BUTTON_C = 38;
  public static final int HEAD = 13;
  public static final int END = 125;
  public static final int SILVER = 58;
  public static final int LIME = 53;
  public static final int IMG = 33;
  public static final int RADIO = 79;
  public static final int HEIGHT = 88;
  public static final int BR = 35;
  public static final int INPUT_C = 24;
  public static final int SCRIPTING_C = 92;
  public static final int RED = 48;
  public static final int COMPARACION = 99;
  public static final int FONT_FAMI = 65;
  public static final int OPTION = 29;
  public static final int FONT_SIZE = 63;
  public static final int SELECTED = 27;
  public static final int INSERT = 129;
  public static final int STRING = 98;
  public static final int ONCLICK = 90;
  public static final int SELECTED_C = 28;
  public static final int AND = 106;
  public static final int MAYOR_IGUAL = 104;
  public static final int LINK_C = 18;
  public static final int GREEN = 55;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "COMILLAS",
  "LLAVE_IZQ",
  "LLAVE_DER",
  "CORCHETE_IZQ",
  "CORCHETE_DER",
  "PARENTESIS_IZQ",
  "PARENTESIS_DER",
  "MENOR",
  "MAYOR",
  "HTML",
  "HTML_C",
  "HEAD",
  "HEAD_C",
  "TITLE",
  "TITLE_C",
  "LINK",
  "LINK_C",
  "BODY",
  "BODY_C",
  "SPAM",
  "SPAN_C",
  "INPUT",
  "INPUT_C",
  "TEXTOAREA",
  "TEXTOAREA_C",
  "SELECTED",
  "SELECTED_C",
  "OPTION",
  "OPTION_C",
  "DIV",
  "DIV_C",
  "IMG",
  "IMG_C",
  "BR",
  "BR_C",
  "BUTTON",
  "BUTTON_C",
  "H1",
  "H1_C",
  "P",
  "P_C",
  "HREF",
  "BACKGROUND",
  "BLACK",
  "OLIVE",
  "TEAL",
  "RED",
  "BLUE",
  "MARRON",
  "NAVY",
  "GRAY",
  "LIME",
  "FUCHSIA",
  "GREEN",
  "WHITE",
  "PURPLE",
  "SILVER",
  "YELLOW",
  "AQUA",
  "HEXADECIMAL",
  "COLOR",
  "FONT_SIZE",
  "PIXEL",
  "FONT_FAMI",
  "COURIER",
  "VERDANA",
  "ARIAL",
  "GENEVA",
  "SANS_SERIF",
  "TEXT_ALIGN",
  "LEFT",
  "RIGHT",
  "CENTER",
  "JUSTITY",
  "TYPE",
  "TEXT",
  "NUMBER",
  "RADIO",
  "CHECKBOX",
  "ID",
  "NAME",
  "COLS",
  "ROWS",
  "CLASS",
  "SRC",
  "WIDTH",
  "HEIGHT",
  "ALT",
  "ONCLICK",
  "SCRIPTING",
  "SCRIPTING_C",
  "ON_LOAD",
  "INTERGER",
  "DECIMAL",
  "BOOLEAN",
  "CHAR",
  "STRING",
  "COMPARACION",
  "DESIGUALDAD",
  "MENOR_QUE",
  "MENOR_IGUAL",
  "MAYOR_QUE",
  "MAYOR_IGUAL",
  "OR",
  "AND",
  "NOT",
  "IGUAL",
  "SUMA",
  "RESTA",
  "PLUS",
  "DIVISION",
  "ASC",
  "DESC",
  "LETIMPAR_NUM",
  "REVERSE",
  "CARACTER_RAMD",
  "NUM_ALEATORIO",
  "ALERT_INFO",
  "EXIT",
  "REDIRECT",
  "INIT",
  "IF",
  "THEN",
  "END",
  "ELSE",
  "REPEAT",
  "HUNTIL",
  "INSERT",
  "WHILE",
  "THENWHILE",
  "FUNTION"
  };
public static final int COMILLA_SIMPLE = 0;
public static final int DOS_PUNTOS = 0;
public static final int CADENA = 0;
public static final int TRUE = 0;
public static final int FALSE = 0;
public static final int NUMERO = 0;
public static final int ENTERO = 0;
public static final int PUNTO_COMA = 0;
public static final int IDENTIFICADOR = 0;
public static final int INTEGER = 0;
}

